version: '3'

services:
  db:
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: testdb
      MYSQL_USER: anas
      MYSQL_PASSWORD: super_secret

  app:
    build: .
    restart: always
    ports:
        - '3000:80'
    volumes:
      - ./spire-app/:/var/www/html/
    depends_on:
      - db